In [88]:
"""
We have: Bel(x) = P(x|e), here e is both e+ and e-
pi(x) = p(x|e-) i.e., evidence from above: So if it's parent is known in distribution
                                            then, x is also known in distribution
lmbda(x) = p(e+|x) i.e., given x what is evidence. It is from below.
Bel(x) = alpha * pi(x) * lambda(x)
BEL(x) is like p(x)

Now, pi(y) = pi(x)*M[0] and normalization: parent's dist and M decides child dist.

also lambda(y) = P(e|y)
and lambda(x) = P(e|x) which is more like Sum p(e, y|x) = P(y|x)*P(e|y, x) and P(e|y.x) = p(e|y)
So lambda(x) = M[0]*lambda(y)
"""
import numpy as np

In [89]:
vNames = ["X", "Y", "Z"]
M = [None, None]
lmbda = [None, None, None]
pi =[None, None, None]
BEL = [None, None, None]

In [90]:
M[0] = np.array([[0.8, 0.1, 0.1], [0.1, 0.8, 0.1], [0.1, 0.1, 0.8]])
M[1] = np.array([ [0.8, 0.2], [0.6, 0.4], [0.5, 0.5] ])

In [91]:
for i in range(len(lmbda)):
    lmbda[i] = np.array([1]*3)

lmbda[2] = np.array([1, 1])

In [93]:
#Going down....
pi[0] = np.array([0.8, 0.1, 0.1])
BEL[0] = pi[0]* lmbda[0]

In [94]:
for i in [1, 2]:
    pi[i] = np.dot(pi[i-1], M[i-1])
    print("pi[",i,"]: ", pi[i])
    BEL[i] = pi[i]*lmbda[i]
    print("BEL[",i,"]: ", BEL[i])

pi[ 1 ]:  [0.66 0.17 0.17]
BEL[ 1 ]:  [0.66 0.17 0.17]
pi[ 2 ]:  [0.715 0.285]
BEL[ 2 ]:  [0.715 0.285]


In [95]:
#Now going up: lambda[1] = [0.8, 0.6, 0.5]
lmbda[1] = np.array([0.8, 0.6, 0.5])
BEL[1] = pi[1] * lmbda[1]
BEL[1] = BEL[1]/sum(BEL[1])
BEL[1], lmbda[1]

(array([0.73846154, 0.14265734, 0.11888112]), array([0.8, 0.6, 0.5]))

In [96]:
lmbda[0] = np.dot(M[0], lmbda[1])
BEL[0] = pi[0]*lmbda[0]
BEL[0] = BEL[0]/sum(BEL[0])

In [97]:
lmbda, pi, M, BEL

([array([0.75, 0.61, 0.54]), array([0.8, 0.6, 0.5]), array([1, 1])],
 [array([0.8, 0.1, 0.1]), array([0.66, 0.17, 0.17]), array([0.715, 0.285])],
 [array([[0.8, 0.1, 0.1],
         [0.1, 0.8, 0.1],
         [0.1, 0.1, 0.8]]), array([[0.8, 0.2],
         [0.6, 0.4],
         [0.5, 0.5]])],
 [array([0.83916084, 0.08531469, 0.07552448]),
  array([0.73846154, 0.14265734, 0.11888112]),
  array([0.715, 0.285])])

In [98]:
#Now again going down...
pi[0] = np.array([0.28, 0.36, 0.36])
BEL[0] = pi[0]*lmbda[0]
BEL[0] /= sum(BEL[0])
BEL

[array([0.33653846, 0.35192308, 0.31153846]),
 array([0.73846154, 0.14265734, 0.11888112]),
 array([0.715, 0.285])]

In [99]:
for i in [1, 2]:
    pi[i] = np.dot(pi[i-1], M[i-1])
    print("pi[",i,"]: ", pi[i])
    BEL[i] = pi[i]*lmbda[i]
    print("BEL[",i,"]: ", BEL[i])

pi[ 1 ]:  [0.296 0.352 0.352]
BEL[ 1 ]:  [0.2368 0.2112 0.176 ]
pi[ 2 ]:  [0.624 0.376]
BEL[ 2 ]:  [0.624 0.376]


In [100]:
BEL[1]/sum(BEL[1])

array([0.37948718, 0.33846154, 0.28205128])